name: PR Workflow

on:
  workflow_dispatch:
    inputs:
      source:
        type: choice
        description: Source branch
        required: true
        options: 
        - dev
        - qa
      dest:
        type: choice
        description: Dest branch
        required: true
        options: 
        - dev
        - qa

jobs:
 createPullRequest:
    runs-on: ubuntu-latest
    steps:

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
         commit-message: Cloud - Update available list
         title: Cloud - Update available list
         body: Cloud - Update available list
         base: main
         labels: automated-pr, Clouds & Regions
         branch: dev
