name: PR Workflow

on:
  workflow_dispatch:
    inputs:
      source:
        type: choice
        description: Source branch
        required: true
        options: 
        - dev
        - qa
      dest:
        type: choice
        description: Dest branch
        required: true
        options: 
        - dev
        - qa

jobs:
 createPullRequest:
    runs-on: ubuntu-latest
    steps:

       - name: create pull request
         run: |
           curl --request POST \
           --url https://api.github.com/repos/${{ github.repository }}/pulls \
           --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
           --header 'content-type: application/json' \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           -d '{"title":"Amazing new feature","body":"Please pull these awesome changes in!","head": "${{ github.event.inputs.source }}","base": "${{ github.event.inputs.dest }}"}'
